Repository input-output-hk/thorn-calculus, pull requests merged in 2023-04, with the labels that each got.

#84 Fix typo in `Foundations`
  src/Thorn_Calculus-Foundations.thy
Labels: type: bugfix

#82 Fix spacing
  src/Thorn_Calculus-Foundations.thy
  src/Thorn_Calculus-Semantics-Synchronous.thy
Labels: type: bugfix

#80 Simplify the proof of `chan_family_distinctness`
  src/Thorn_Calculus-Foundations.thy
Labels: type: improvement

#77 Port `Thorn_Calculus-Experiments` from legacy repository
  src/Thorn_Calculus-Examples.thy
Labels: type: enhancement

#71 Add no-mobility versions of transition system rules
  src/Thorn_Calculus-Semantics-Synchronous.thy
Labels: type: enhancement

#76 Add `family_uncurry_after_` lemmas for derived constructs
  src/Thorn_Calculus-Processes.thy
  src/Thorn_Calculus-Semantics-Synchronous.thy
Labels: type: enhancement
